[package]
name = "O-Test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "piscine-test"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
indicatif = "0.17.11"
once_cell = "1.21.3"
